// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteChecker.Database;

#nullable disable

namespace SiteChecker.Database.Migrations
{
    [DbContext(typeof(SiteCheckerDbContext))]
    partial class SiteCheckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SiteChecker.Database.Model.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysTakeScreenshot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnownFailuresThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScraperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseVpn")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DiscordConfig", "SiteChecker.Database.Model.Site.DiscordConfig#DiscordConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<ulong?>("ChannelId");

                            b1.Property<bool>("FailureEnabled");

                            b1.Property<bool>("SuccessEnabled");

                            b1.ToJson("DiscordConfig");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PushoverConfig", "SiteChecker.Database.Model.Site.PushoverConfig#PushoverConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("FailurePriority");

                            b1.Property<int?>("SuccessPriority");

                            b1.ToJson("PushoverConfig");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Schedule", "SiteChecker.Database.Model.Site.Schedule#SiteSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Enabled");

                            b1.Property<TimeOnly?>("End");

                            b1.Property<uint?>("Interval");

                            b1.Property<TimeOnly?>("Start");

                            b1.ToJson("Schedule");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ScraperId")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.SiteCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DoneDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("VpnLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SiteChecks");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.SiteCheckScreenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SiteCheckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteCheckId")
                        .IsUnique();

                    b.ToTable("SiteCheckScreenshots");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.SiteCheck", b =>
                {
                    b.HasOne("SiteChecker.Database.Model.Site", "Site")
                        .WithMany("SiteChecks")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.SiteCheckScreenshot", b =>
                {
                    b.HasOne("SiteChecker.Database.Model.SiteCheck", "SiteCheck")
                        .WithOne("Screenshot")
                        .HasForeignKey("SiteChecker.Database.Model.SiteCheckScreenshot", "SiteCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteCheck");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.Site", b =>
                {
                    b.Navigation("SiteChecks");
                });

            modelBuilder.Entity("SiteChecker.Database.Model.SiteCheck", b =>
                {
                    b.Navigation("Screenshot");
                });
#pragma warning restore 612, 618
        }
    }
}
