<Project Sdk="MSTest.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Backend\Backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

</Project>
